[[bin]]
name = "unicode-ident-diagram"
path = "Source/main.rs"

[package]
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
name = "unicode-ident-generate"
publish = false
version = "0.0.0"
