[[bin]]
name = "unicode-ident-diagram"
path = "Source/main.rs"

[dependencies]
image = "0.25.5"
unicode-id-start = { path = ".." }

[package]
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
name = "unicode-ident-diagram"
publish = false
version = "0.0.0"
